"$schema" = 'https://starship.rs/config-schema.json'

[character]
success_symbol = "[âœ](#EBCB8B) "
error_symbol = "[âœ—](#BF616A) "


[battery]
full_symbol = "ğŸ”‹"
charging_symbol = "âš¡ï¸"
discharging_symbol = "ğŸ’€"


[git_branch]
disabled = true
symbol = "ğŸŒ± "


[git_status]
disabled=true
conflicted = "ğŸ‘¥"
ahead = "ğŸğŸ’¨"
behind = "âª"
diverged = "ğŸ˜µ"
untracked = "ğŸ¤·â€"
stashed = "ğŸ“¦"
modified = "ğŸ“"
staged = '[ â• \($count\)](yellow)'
renamed = "ğŸ‘…"
deleted = "ğŸ”¥"
